# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'firstMainWin.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setEnabled(True)
        MainWindow.resize(908, 572)
        MainWindow.setMouseTracking(True)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.help_tab = QtWidgets.QTabWidget(self.centralwidget)
        self.help_tab.setGeometry(QtCore.QRect(10, 0, 891, 521))
        self.help_tab.setObjectName("help_tab")
        self.codingConvert_tab = QtWidgets.QWidget()
        self.codingConvert_tab.setObjectName("codingConvert_tab")
        self.layoutWidget = QtWidgets.QWidget(self.codingConvert_tab)
        self.layoutWidget.setGeometry(QtCore.QRect(0, 10, 891, 481))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout.setSizeConstraint(QtWidgets.QLayout.SetMinimumSize)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.inputText = QtWidgets.QPlainTextEdit(self.layoutWidget)
        self.inputText.setObjectName("inputText")
        self.verticalLayout.addWidget(self.inputText)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.decode_rbtn = QtWidgets.QRadioButton(self.layoutWidget)
        self.decode_rbtn.setCheckable(True)
        self.decode_rbtn.setChecked(True)
        self.decode_rbtn.setObjectName("decode_rbtn")
        self.encode_buttonGroup = QtWidgets.QButtonGroup(MainWindow)
        self.encode_buttonGroup.setObjectName("encode_buttonGroup")
        self.encode_buttonGroup.addButton(self.decode_rbtn)
        self.verticalLayout_4.addWidget(self.decode_rbtn)
        self.encode_rbtn = QtWidgets.QRadioButton(self.layoutWidget)
        self.encode_rbtn.setCheckable(True)
        self.encode_rbtn.setChecked(False)
        self.encode_rbtn.setObjectName("encode_rbtn")
        self.encode_buttonGroup.addButton(self.encode_rbtn)
        self.verticalLayout_4.addWidget(self.encode_rbtn)
        self.gridLayout.addLayout(self.verticalLayout_4, 0, 0, 1, 1)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.pushButton = QtWidgets.QPushButton(self.layoutWidget)
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout_2.addWidget(self.pushButton)
        self.pushButton_3 = QtWidgets.QPushButton(self.layoutWidget)
        self.pushButton_3.setObjectName("pushButton_3")
        self.horizontalLayout_2.addWidget(self.pushButton_3)
        self.gridLayout.addLayout(self.horizontalLayout_2, 1, 6, 1, 1)
        self.html_btn = QtWidgets.QPushButton(self.layoutWidget)
        self.html_btn.setObjectName("html_btn")
        self.gridLayout.addWidget(self.html_btn, 1, 4, 1, 1)
        self.unicode_btn = QtWidgets.QPushButton(self.layoutWidget)
        self.unicode_btn.setObjectName("unicode_btn")
        self.gridLayout.addWidget(self.unicode_btn, 0, 5, 1, 1)
        self.base64_btn = QtWidgets.QPushButton(self.layoutWidget)
        self.base64_btn.setObjectName("base64_btn")
        self.gridLayout.addWidget(self.base64_btn, 1, 2, 1, 1)
        self.hex_btn = QtWidgets.QPushButton(self.layoutWidget)
        self.hex_btn.setObjectName("hex_btn")
        self.gridLayout.addWidget(self.hex_btn, 0, 4, 1, 1)
        self.exchange_btn = QtWidgets.QPushButton(self.layoutWidget)
        self.exchange_btn.setObjectName("exchange_btn")
        self.gridLayout.addWidget(self.exchange_btn, 0, 8, 1, 1)
        self.clear_btn = QtWidgets.QPushButton(self.layoutWidget)
        self.clear_btn.setObjectName("clear_btn")
        self.gridLayout.addWidget(self.clear_btn, 1, 8, 1, 1)
        self.url_btn = QtWidgets.QPushButton(self.layoutWidget)
        self.url_btn.setObjectName("url_btn")
        self.gridLayout.addWidget(self.url_btn, 0, 2, 1, 1)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.utf8_rbtn = QtWidgets.QRadioButton(self.layoutWidget)
        self.utf8_rbtn.setChecked(True)
        self.utf8_rbtn.setAutoRepeat(True)
        self.utf8_rbtn.setObjectName("utf8_rbtn")
        self.code_buttonGroup = QtWidgets.QButtonGroup(MainWindow)
        self.code_buttonGroup.setObjectName("code_buttonGroup")
        self.code_buttonGroup.addButton(self.utf8_rbtn)
        self.verticalLayout_3.addWidget(self.utf8_rbtn)
        self.gbk_rbtm = QtWidgets.QRadioButton(self.layoutWidget)
        self.gbk_rbtm.setObjectName("gbk_rbtm")
        self.code_buttonGroup.addButton(self.gbk_rbtm)
        self.verticalLayout_3.addWidget(self.gbk_rbtm)
        self.gridLayout.addLayout(self.verticalLayout_3, 1, 0, 1, 1)
        self.timestamp_btn = QtWidgets.QPushButton(self.layoutWidget)
        self.timestamp_btn.setObjectName("timestamp_btn")
        self.gridLayout.addWidget(self.timestamp_btn, 1, 5, 1, 1)
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.str2_lineEdit = QtWidgets.QLineEdit(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.str2_lineEdit.sizePolicy().hasHeightForWidth())
        self.str2_lineEdit.setSizePolicy(sizePolicy)
        self.str2_lineEdit.setObjectName("str2_lineEdit")
        self.gridLayout_2.addWidget(self.str2_lineEdit, 0, 1, 1, 1)
        self.str1_lineEdit = QtWidgets.QLineEdit(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.str1_lineEdit.sizePolicy().hasHeightForWidth())
        self.str1_lineEdit.setSizePolicy(sizePolicy)
        self.str1_lineEdit.setMaxLength(12)
        self.str1_lineEdit.setObjectName("str1_lineEdit")
        self.gridLayout_2.addWidget(self.str1_lineEdit, 0, 0, 1, 1)
        self.replace_btn = QtWidgets.QPushButton(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.replace_btn.sizePolicy().hasHeightForWidth())
        self.replace_btn.setSizePolicy(sizePolicy)
        self.replace_btn.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.replace_btn.setObjectName("replace_btn")
        self.gridLayout_2.addWidget(self.replace_btn, 1, 0, 1, 1)
        self.regex_btn = QtWidgets.QPushButton(self.layoutWidget)
        self.regex_btn.setObjectName("regex_btn")
        self.gridLayout_2.addWidget(self.regex_btn, 1, 1, 1, 1)
        self.gridLayout.addLayout(self.gridLayout_2, 0, 6, 1, 1)
        self.removeSpace_btn = QtWidgets.QPushButton(self.layoutWidget)
        self.removeSpace_btn.setObjectName("removeSpace_btn")
        self.gridLayout.addWidget(self.removeSpace_btn, 0, 7, 1, 1)
        self.removeReturn_btn = QtWidgets.QPushButton(self.layoutWidget)
        self.removeReturn_btn.setObjectName("removeReturn_btn")
        self.gridLayout.addWidget(self.removeReturn_btn, 1, 7, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout)
        self.outputText = QtWidgets.QPlainTextEdit(self.layoutWidget)
        self.outputText.setObjectName("outputText")
        self.verticalLayout.addWidget(self.outputText)
        self.help_tab.addTab(self.codingConvert_tab, "")
        self.encryption_decryption_tab = QtWidgets.QWidget()
        self.encryption_decryption_tab.setObjectName("encryption_decryption_tab")
        self.help_tab.addTab(self.encryption_decryption_tab, "")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.plainTextEdit = QtWidgets.QPlainTextEdit(self.tab)
        self.plainTextEdit.setGeometry(QtCore.QRect(0, 0, 891, 501))
        self.plainTextEdit.setObjectName("plainTextEdit")
        self.help_tab.addTab(self.tab, "")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 908, 22))
        self.menubar.setObjectName("menubar")
        self.menuAbout = QtWidgets.QMenu(self.menubar)
        self.menuAbout.setObjectName("menuAbout")
        self.menuAuthor = QtWidgets.QMenu(self.menuAbout)
        self.menuAuthor.setObjectName("menuAuthor")
        MainWindow.setMenuBar(self.menubar)
        self.actionArch = QtWidgets.QAction(MainWindow)
        self.actionArch.setObjectName("actionArch")
        self.menuAuthor.addAction(self.actionArch)
        self.menuAbout.addAction(self.menuAuthor.menuAction())
        self.menubar.addAction(self.menuAbout.menuAction())

        self.retranslateUi(MainWindow)
        self.help_tab.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "编码小工具"))
        self.decode_rbtn.setText(_translate("MainWindow", "解码(decode)"))
        self.encode_rbtn.setText(_translate("MainWindow", "编码(encode)"))
        self.pushButton.setText(_translate("MainWindow", "MD5"))
        self.pushButton_3.setText(_translate("MainWindow", "SHA256"))
        self.html_btn.setText(_translate("MainWindow", "HTML实体字符"))
        self.unicode_btn.setText(_translate("MainWindow", "Unicode"))
        self.base64_btn.setText(_translate("MainWindow", "Base64"))
        self.hex_btn.setText(_translate("MainWindow", "HEX"))
        self.exchange_btn.setText(_translate("MainWindow", "Exchange"))
        self.clear_btn.setText(_translate("MainWindow", "Clear All"))
        self.url_btn.setText(_translate("MainWindow", "URL"))
        self.utf8_rbtn.setText(_translate("MainWindow", "UTF-8"))
        self.gbk_rbtm.setText(_translate("MainWindow", "GBK"))
        self.timestamp_btn.setText(_translate("MainWindow", "时间戳"))
        self.replace_btn.setText(_translate("MainWindow", "文本替换"))
        self.regex_btn.setText(_translate("MainWindow", "正则替换"))
        self.removeSpace_btn.setText(_translate("MainWindow", "清除空格"))
        self.removeReturn_btn.setText(_translate("MainWindow", "清除回车"))
        self.help_tab.setTabText(self.help_tab.indexOf(self.codingConvert_tab), _translate("MainWindow", "编码转换"))
        self.help_tab.setTabText(self.help_tab.indexOf(self.encryption_decryption_tab), _translate("MainWindow", "加解密"))
        self.plainTextEdit.setPlainText(_translate("MainWindow", "支持的字符集：GBK、UTF-8\n"
                                                                 "支持编码方式：URL、Base64、Hex、时间戳转换、HTML实体字符（待完善）\n"
                                                                 "支持的文本操作：文本替换、正则替换(待开发)、清空空格、清空回车\n"
                                                                 "\n"
                                                                 "\n"
                                                                 "Hex：\n"
                                                                 "> 注意：编码格式需要用空格隔开\n"
                                                                 "Hex编码：31 32 33 \n"
                                                                 "Hex解码：1 2 3\n"
                                                                 "\n"
                                                                 "\n"
                                                                 "时间戳转换：\n"
                                                                 "编码格式：1544122322\n"
                                                                 "解码格式：2018-12-07 02:52:02\n"
                                                                 "\n"
                                                                 ""))
        self.help_tab.setTabText(self.help_tab.indexOf(self.tab), _translate("MainWindow", "help"))
        self.menuAbout.setTitle(_translate("MainWindow", "About"))
        self.menuAuthor.setTitle(_translate("MainWindow", "Author"))
        self.actionArch.setText(_translate("MainWindow", "Ar3hang1"))
